"""initial schema - all core tables

Revision ID: 33fba512e256
Revises: 
Create Date: 2026-06-24 19:40:38.495965
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33fba512e256'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('admin_email', sa.String(length=255), nullable=False),
    sa.Column('admin_password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_email'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('trips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('destination_city', sa.String(length=255), nullable=False),
    sa.Column('destination_iata', sa.String(length=10), nullable=False),
    sa.Column('arrival_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('max_arrival_spread_minutes', sa.Integer(), nullable=False),
    sa.Column('friction_weight_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('intake_token', sa.String(length=100), nullable=False),
    sa.Column('intake_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_travelers', sa.Integer(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('intake_token')
    )
    op.create_table('clusters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('origin_iata', sa.String(length=10), nullable=False),
    sa.Column('cluster_key', sa.String(length=100), nullable=False, comment="Composite key: '{origin_iata}_{date_bucket}' for grouping."),
    sa.Column('traveler_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('aggregated_constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Pre-computed: min budget, latest unblock time, earliest departure, seat count.'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consensus_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_cost_cents', sa.Integer(), nullable=False, comment="Sum of all travelers' flight costs in cents."),
    sa.Column('max_arrival_spread_actual_minutes', sa.Integer(), nullable=False, comment='Actual time spread between earliest and latest cluster arrivals.'),
    sa.Column('total_negotiation_rounds', sa.Integer(), nullable=False, comment='How many rounds it took to reach consensus.'),
    sa.Column('total_tokens_used', sa.Integer(), nullable=False, comment='Total LLM tokens consumed across all rounds.'),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False, comment='Proposal expires at this time. Auto-revalidation kicks in.'),
    sa.Column('confirmation_deadline', sa.DateTime(timezone=True), nullable=True, comment='All travelers must confirm by this deadline.'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('negotiation_rounds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('llm_input_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Exact payload sent to the LLM (system prompt + user message).'),
    sa.Column('llm_output_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Raw LLM response before Pydantic validation.'),
    sa.Column('tokens_used', sa.Integer(), nullable=True, comment='Total tokens consumed (prompt + completion).'),
    sa.Column('convergence_adjustment', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Adjustment hint from orchestrator if convergence failed.'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('travelers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('origin_city', sa.String(length=255), nullable=True),
    sa.Column('origin_iata', sa.String(length=10), nullable=True),
    sa.Column('hard_budget_cents', sa.Integer(), nullable=True, comment='Maximum budget in cents. Never use floats for money.'),
    sa.Column('blocked_windows_utc', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Array of {"start": "ISO8601", "end": "ISO8601"} UTC windows when traveler CANNOT travel.'),
    sa.Column('soft_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Unstructured preferences: seat preference, airline preference, avoid redeye, etc.'),
    sa.Column('confirmation_status', sa.String(length=50), nullable=False),
    sa.Column('constraints_submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flight_proposals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('round_id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('flight_number', sa.String(length=20), nullable=False),
    sa.Column('airline', sa.String(length=255), nullable=True),
    sa.Column('origin_iata', sa.String(length=10), nullable=False),
    sa.Column('destination_iata', sa.String(length=10), nullable=False),
    sa.Column('departure_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('arrival_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('stops', sa.Integer(), nullable=False),
    sa.Column('layover_minutes', sa.Integer(), nullable=False),
    sa.Column('cabin_class', sa.String(length=50), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=False, comment='Price per person in cents.'),
    sa.Column('total_cost_score', sa.Integer(), nullable=False, comment='Friction-adjusted total cost: price + (layover_hours × friction_weight).'),
    sa.Column('available_seats', sa.Integer(), nullable=True),
    sa.Column('provider_source', sa.String(length=50), nullable=False, comment="'amadeus', 'duffel', or 'serpapi'."),
    sa.Column('provider_booking_id', sa.String(length=500), nullable=True, comment='Provider-specific ID for deep-linking to exact fare.'),
    sa.Column('booking_deep_link', sa.String(length=2000), nullable=True, comment='Direct URL to book this exact flight.'),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('raw_provider_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Full provider API response for debugging and audit.'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['round_id'], ['negotiation_rounds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('traveler_itineraries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('consensus_id', sa.UUID(), nullable=False),
    sa.Column('traveler_id', sa.UUID(), nullable=False),
    sa.Column('proposal_id', sa.UUID(), nullable=True),
    sa.Column('booking_deep_link', sa.String(length=2000), nullable=True, comment='Direct URL for this traveler to book their assigned flight.'),
    sa.Column('traveler_confirmation', sa.String(length=50), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['consensus_id'], ['consensus_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposal_id'], ['flight_proposals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['traveler_id'], ['travelers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('traveler_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('traveler_itineraries')
    op.drop_table('flight_proposals')
    op.drop_table('travelers')
    op.drop_table('negotiation_rounds')
    op.drop_table('consensus_results')
    op.drop_table('clusters')
    op.drop_table('trips')
    op.drop_table('organizations')
    # ### end Alembic commands ###
