import uuid
from datetime import datetime, timezone
from sqlalchemy import String, Boolean, DateTime, ForeignKey, Enum, Float, Integer
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship
import enum

from maci_core.database import Base

class MeetupStatus(str, enum.Enum):
    open = "open"
    locked = "locked" # No more participants
    active = "active" # Currently happening
    completed = "completed"
    cancelled = "cancelled"

class MeetupMemberStatus(str, enum.Enum):
    pending = "pending" # Escrow authorized, waiting for check-in
    checked_in = "checked_in" # User arrived, escrow can be released
    flaked = "flaked" # User no-show, escrow captured
    cancelled = "cancelled" # Meetup cancelled, escrow released

class Meetup(Base):
    """
    Micro-commitment event (e.g. coffee, co-working).
    Used for local vibes checks.
    """
    __tablename__ = "meetups"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    host_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str] = mapped_column(String(1000), nullable=True)
    
    # Geospatial Coordinates
    latitude: Mapped[float] = mapped_column(Float, nullable=False)
    longitude: Mapped[float] = mapped_column(Float, nullable=False)
    
    start_time: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    
    # Escrow logic
    escrow_amount_cents: Mapped[int] = mapped_column(Integer, default=500) # $5 default
    
    status: Mapped[MeetupStatus] = mapped_column(Enum(MeetupStatus), default=MeetupStatus.open)
    check_in_pin: Mapped[str] = mapped_column(String(10), nullable=False) # e.g. "4921" generated by host
    
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))

    host = relationship("User")
    members: Mapped[list["MeetupMember"]] = relationship(back_populates="meetup", cascade="all, delete-orphan")

class MeetupMember(Base):
    """
    Tracks users who join a Meetup and their Escrow state.
    """
    __tablename__ = "meetup_members"
    
    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    meetup_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("meetups.id", ondelete="CASCADE"), nullable=False)
    user_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    
    stripe_payment_intent_id: Mapped[str] = mapped_column(String(255), nullable=True)
    status: Mapped[MeetupMemberStatus] = mapped_column(Enum(MeetupMemberStatus), default=MeetupMemberStatus.pending)
    
    joined_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
    
    meetup = relationship("Meetup", back_populates="members")
    user = relationship("User")
